[build]
  command = "bun run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[functions."release-payouts"]
  schedule = "*/15 * * * *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
